/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DataSourceEdit {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDataSourceEditElement extends Components.DataSourceEdit, HTMLStencilElement {
    }
    var HTMLDataSourceEditElement: {
        prototype: HTMLDataSourceEditElement;
        new (): HTMLDataSourceEditElement;
    };
    interface HTMLElementTagNameMap {
        "data-source-edit": HTMLDataSourceEditElement;
    }
}
declare namespace LocalJSX {
    interface DataSourceEdit {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "data-source-edit": DataSourceEdit;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "data-source-edit": LocalJSX.DataSourceEdit & JSXBase.HTMLAttributes<HTMLDataSourceEditElement>;
        }
    }
}
